"""
AVIRA AI Agent 6 – Report Generator
======================================
Assembles the complete, human-readable health monitoring report
from all upstream agent outputs. Produces both a structured JSON
response (for the API) and a formatted plain-text report (for TXT logging).

IMPORTANT: This report is a health monitoring tool.
           It is NOT a veterinary diagnosis.
"""

import logging
from datetime import datetime, timezone
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class ReportGeneratorAgent:
    """
    Agent 6 – Report Generator.

    Compiles all AI pipeline outputs into a complete, formatted health report.
    """

    AGENT_ID = "REPORT_GENERATOR"
    DISCLAIMER = (
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "DISCLAIMER: This report is generated by an AI-powered health\n"
        "monitoring system (AVIRA by PRANIVA). It is NOT a veterinary\n"
        "diagnosis. All health alerts represent monitoring observations\n"
        "only. Always consult a licensed veterinarian for medical decisions.\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    )

    def generate(
        self,
        cow_id: str,
        session_id: str,
        sensor_data: dict,
        manual_data: Optional[dict],
        vital_analysis: dict,
        disease_results: dict,
        validation_results: dict,
        recommendation_output: dict,
        vision_findings: Optional[dict] = None,
    ) -> dict:
        """
        Generate the complete health monitoring report.

        Returns:
            Dict with 'json_report' (structured) and 'text_report' (plain-text)
        """
        logger.info("[%s] Generating report for %s / %s", self.AGENT_ID, cow_id, session_id)

        ts = datetime.now(timezone.utc).isoformat()
        disease_probs = (
            disease_results.get("disease_candidates")
            or validation_results.get("validated_probabilities", [])
        )
        top_disease = disease_probs[0] if disease_probs else None
        urgency = recommendation_output.get("urgency_level", "LOW")
        alert_level = vital_analysis.get("alert_level", "NORMAL")

        # ── JSON Report (structured, for API) ────────────────────────────
        json_report = {
            "report_id": f"RPT_{session_id}",
            "generated_at": ts,
            "system": "AVIRA v1.0 by PRANIVA",
            "cow_id": cow_id,
            "session_id": session_id,
            "health_summary": {
                "alert_level": alert_level,
                "urgency": urgency,
                "vet_required": recommendation_output.get("vet_required", False),
                "overall_stress_index": vital_analysis.get("stress_index", 0.0),
                "data_quality": validation_results.get("data_quality", {}).get("tier", "UNKNOWN"),
                "summary": recommendation_output.get("summary", ""),
            },
            "vitals": {
                "heart_rate": self._format_vital(vital_analysis, "heart_rate"),
                "spo2": self._format_vital(vital_analysis, "spo2"),
                "motion": self._format_vital(vital_analysis, "motion"),
                "temperature": self._format_vital(vital_analysis, "temperature"),
            },
            "manual_observations": {
                "temperature_c": manual_data.get("temperature") if manual_data else None,
                "milk_production_lday": manual_data.get("milk_production") if manual_data else None,
                "appetite_score": manual_data.get("appetite") if manual_data else None,
                "rumination_score": manual_data.get("rumination") if manual_data else None,
                "water_intake_lday": manual_data.get("water_intake") if manual_data else None,
                "feed_intake_kgday": manual_data.get("feed_intake") if manual_data else None,
                "observations": manual_data.get("observations") if manual_data else None,
            },
            "disease_analysis": {
                "disclaimer": "These are probability indicators, NOT diagnoses.",
                "top_3_candidates": [
                    {
                        "rank": idx + 1,
                        "disease": d["disease"],
                        "probability": d["probability"],
                        "confidence_tier": d.get("confidence", "LOW"),
                        "urgency": d.get("urgency", "MEDIUM"),
                        "vet_required": d.get("vet_required", False),
                        "matched_evidence_count": len(
                            d.get("evidence_matched") or d.get("matched_evidence", [])
                        ),
                        "top_evidence": (
                            d.get("evidence_matched") or d.get("matched_evidence", [])
                        )[:3],
                        "treatment_info": d.get("treatment_info", {}),
                    }
                    for idx, d in enumerate(disease_probs[:3])
                ],
            },
            "vision_analysis": {
                "performed": vision_findings is not None,
                "has_detections": vision_findings.get("has_detections", False) if vision_findings else False,
                "detected_conditions": vision_findings.get("detected_conditions", []) if vision_findings else [],
                "summary": vision_findings.get("visual_summary", "No image provided") if vision_findings else "No image provided",
            },
            "recommendations": recommendation_output.get("recommendations", []),
            "cross_validation": {
                "issues": validation_results.get("issues_found", []),
                "adjustments": validation_results.get("adjustments_made", []),
                "reportable_alerts": validation_results.get("reportable_alerts", []),
            },
            "pipeline_confidence": round(
                (vital_analysis.get("confidence", 0.5) +
                 disease_results.get("agent_confidence", disease_results.get("confidence", 0.5)) +
                 recommendation_output.get("confidence", 0.5)) / 3, 3
            ),
        }

        # ── Plain-Text Report ─────────────────────────────────────────────
        text_report = self._build_text_report(
            cow_id, session_id, ts, json_report
        )

        result = {
            "agent": self.AGENT_ID,
            "step": "Report Generation",
            "json_report": json_report,
            "text_report": text_report,
            "confidence": json_report["pipeline_confidence"],
            "evidence": [f"Report generated: {ts}"],
        }

        return result

    # ─────────────────────────────────────────────
    #  Text Report Builder
    # ─────────────────────────────────────────────

    def _build_text_report(self, cow_id: str, session_id: str, ts: str, report: dict) -> str:
        """Build a formatted plain-text report string."""
        lines = []
        add = lines.append

        add("╔══════════════════════════════════════════════════════════════╗")
        add("║           AVIRA LIVESTOCK HEALTH MONITORING REPORT           ║")
        add("║              PRANIVA – Advanced Veterinary AI               ║")
        add("╚══════════════════════════════════════════════════════════════╝")
        add("")
        add(f"  Report ID  : {report['report_id']}")
        add(f"  Generated  : {ts}")
        add(f"  Animal ID  : {cow_id}")
        add(f"  Session    : {session_id}")
        add("")
        add(self.DISCLAIMER)
        add("")

        # ── Health Summary ──────────────────────────────────────────────
        hs = report["health_summary"]
        add("┌─────────────────────────────────────────────────────────────┐")
        add("│                      HEALTH SUMMARY                        │")
        add("└─────────────────────────────────────────────────────────────┘")
        add(f"  Alert Level   : {hs['alert_level']}")
        add(f"  Urgency       : {hs['urgency']}")
        add(f"  Vet Required  : {'⚠️  YES' if hs['vet_required'] else 'No'}")
        add(f"  Stress Index  : {hs['overall_stress_index']:.3f}")
        add(f"  Data Quality  : {hs['data_quality']}")
        add("")
        add(f"  Summary: {hs['summary']}")
        add("")

        # ── Vital Signs ─────────────────────────────────────────────────
        add("┌─────────────────────────────────────────────────────────────┐")
        add("│                      VITAL SIGNS                           │")
        add("└─────────────────────────────────────────────────────────────┘")
        for name, vital in report["vitals"].items():
            status = vital.get("status", "N/A")
            value = vital.get("value", "N/A")
            add(f"  {name.replace('_', ' ').title():<20}: {value}  [{status}]")
        add("")

        # ── Manual Observations ─────────────────────────────────────────
        add("┌─────────────────────────────────────────────────────────────┐")
        add("│                  MANUAL OBSERVATIONS                       │")
        add("└─────────────────────────────────────────────────────────────┘")
        mo = report["manual_observations"]
        add(f"  Temperature       : {mo.get('temperature_c', 'N/A')} °C")
        add(f"  Milk Production   : {mo.get('milk_production_lday', 'N/A')} L/day")
        add(f"  Appetite          : {mo.get('appetite_score', 'N/A')} /10")
        add(f"  Rumination        : {mo.get('rumination_score', 'N/A')} /10")
        add(f"  Water Intake      : {mo.get('water_intake_lday', 'N/A')} L/day")
        add(f"  Feed Intake       : {mo.get('feed_intake_kgday', 'N/A')} kg/day")
        if mo.get("observations"):
            add(f"  Observations      : {mo['observations']}")
        add("")

        # ── Disease Analysis ─────────────────────────────────────────────
        add("┌─────────────────────────────────────────────────────────────┐")
        add("│              AI HEALTH INDICATOR ANALYSIS                  │")
        add("└─────────────────────────────────────────────────────────────┘")
        add("  ⚠️  These are probability indicators, NOT diagnoses.")
        add("")
        for candidate in report["disease_analysis"]["top_3_candidates"]:
            add(f"  #{candidate['rank']} {candidate['disease']}")
            add(f"     Probability  : {candidate['probability']:.1%}")
            add(f"     Confidence   : {candidate['confidence_tier']}")
            add(f"     Urgency      : {candidate['urgency']}")
            add(f"     Evidence     :")
            for ev in candidate["top_evidence"]:
                add(f"       + {ev}")
            add("")

        # ── Vision Analysis ──────────────────────────────────────────────
        va = report["vision_analysis"]
        if va["performed"]:
            add("┌─────────────────────────────────────────────────────────────┐")
            add("│                    VISION ANALYSIS                         │")
            add("└─────────────────────────────────────────────────────────────┘")
            add(f"  Detections Found : {'Yes' if va['has_detections'] else 'No'}")
            for dc in va.get("detected_conditions", []):
                add(f"  • {dc['display_name']} ({dc['confidence']:.1%})")
            add(f"  Summary: {va['summary']}")
            add("")

        # ── Recommendations ──────────────────────────────────────────────
        add("┌─────────────────────────────────────────────────────────────┐")
        add("│                    RECOMMENDATIONS                         │")
        add("└─────────────────────────────────────────────────────────────┘")
        for rec in report["recommendations"]:
            add(f"  [{rec['category']}] {rec['action']}")
        add("")

        # ── Footer ──────────────────────────────────────────────────────
        add("─" * 64)
        add("  AVIRA v1.0 | PRANIVA | AI-Powered Livestock Health Monitoring")
        add(f"  Pipeline Confidence: {report['pipeline_confidence']:.1%}")
        add("─" * 64)

        return "\n".join(lines)

    def _format_vital(self, vital_analysis: dict, key: str) -> dict:
        """Extract and format a single vital from the analysis output."""
        vitals = vital_analysis.get("vitals", {})
        v = vitals.get(key, {})
        return {
            "value": v.get("value"),
            "status": v.get("status", "UNKNOWN"),
            "finding": v.get("finding", "No data"),
        }
